
--DROP TABLE if exists DEVICES CASCADE; 
--DROP TABLE if exists GATEWAYS CASCADE;  

CREATE TABLE GATEWAYS (
   ID  BIGINT AUTO_INCREMENT,
   UNIQUE_SERIAL_NUMBER VARCHAR(50),
   GATEWAY_NAME VARCHAR(255),
   IP_ADDRESS VARCHAR(255),
   PRIMARY KEY (ID),
   UNIQUE KEY SERIAL_NUMBER_UNIQUE (UNIQUE_SERIAL_NUMBER)
);


CREATE TABLE DEVICES (
   DEVICE_ID  BIGINT AUTO_INCREMENT,
   UNIQUE_NUMBER VARCHAR(200),
   VENDOR VARCHAR(200),
   CREATED_ON DATETIME,
   STATUS VARCHAR(50),
   GATEWAY_ID BIGINT,
   PRIMARY KEY (DEVICE_ID),
   UNIQUE KEY UNIQUE_NUMBER_UNIQUE (UNIQUE_NUMBER),
   CONSTRAINT FK_GATEWAY_DEVICE FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAYS (ID)
);


INSERT INTO GATEWAYS(ID, UNIQUE_SERIAL_NUMBER, GATEWAY_NAME, IP_ADDRESS)
	VALUES (1, 'DFGF111111FD11', 'Acer', '10.0.1.1');

INSERT INTO GATEWAYS(ID, UNIQUE_SERIAL_NUMBER, GATEWAY_NAME, IP_ADDRESS)
	VALUES (2, 'ERFG222222FG22', 'gateway_2', '10.0.2.1');

INSERT INTO GATEWAYS(ID, UNIQUE_SERIAL_NUMBER, GATEWAY_NAME, IP_ADDRESS)
	VALUES (3, 'YUIG333333R33', 'gateway_3', '10.0.3.1');



INSERT INTO DEVICES(DEVICE_ID, UNIQUE_NUMBER, VENDOR, CREATED_ON, STATUS, GATEWAY_ID)
	VALUES (1, '124323453', 'Ericsson', '2020-03-18 14:59:35', 'OFFLINE' , 1);

INSERT INTO DEVICES(DEVICE_ID, UNIQUE_NUMBER, VENDOR, CREATED_ON, STATUS, GATEWAY_ID)
	VALUES (2, '22222334', 'Intel', '2020-10-10 14:59:35', 'OFFLINE' , 1);

INSERT INTO DEVICES(DEVICE_ID, UNIQUE_NUMBER, VENDOR, CREATED_ON, STATUS, GATEWAY_ID)
	VALUES (3, '33334555', 'Realtek', '2021-03-18 15:59:35', 'ONLINE' , 3);