server:
  port: 8080
  servlet:
    context-path: /gateway/rest/

logging:
  level: 
    root: info
    
spring:
  application:
    name: gateway-Service
  datasource:
    url: jdbc:h2:mem:gatewayDB
    driver-class-name: org.h2.Driver
    username: admin
    password: P@$$w0rd
    schema: classpath:/script/schema.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      username: admin
      password: P@$$w0rd

# Enabling H2 Console
#  h2:
#    console:
#      enabled: true
#      path: /h2
